[phases.setup]
nixPkgs = ["nodejs", "python3", "cmake", "gcc"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install zstandard",
  "/app/venv/bin/pip install ./luauvmp-engine/luau-vmp-deobf-main --no-deps"
]

[start]
cmd = "node server.js"
